#!/bin/sh

case $1 in
	commit)
		layerno=$(find /opt/cluster/layers -type d -mindepth 1 -maxdepth 1 | wc -l)
		layer=/opt/cluster/layers/layer$(printf "%03d" $layerno)
		mkdir -p $layer
		find /opt/cluster/init -type f -mindepth 1 -maxdepth 1 | xargs -I {} mv {} $layer/
		chmod +x -R $layer
	;;
	init)
		cd /opt/cluster
		mkdir done
		cd layers
		for layer in *; do
			[ ! -d $layer ] && continue
			mkdir -p ../done/$layer
			for s in $layer/*; do
				[ ! -f $s ] && continue
				echo "processing $s"
				sh $s && mv $s ../done/$s
			done
			rmdir $layer
		done
		cd ..
		rmdir layers
	;;
esac
